GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzE0NjU0MDc5LCJleHAiOjE3MTQ2NTQxMjR9.BdFQxEwXSb8OJ8xVfKIYrOBVif934Ln3dM28NzAdAEs



###
POST http://localhost:4000/token

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzE0NTE5MjMyfQ.ogL59jrTbCeqRmmimxDB5eMu8RGYb0VDcE9qYQMnePs"

}



###
DELETE http://localhost:4000/logout

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzE0NTE5MjMyfQ.ogL59jrTbCeqRmmimxDB5eMu8RGYb0VDcE9qYQMnePs"

}


###

POST http://localhost:4000/login
content-Type: application/json
    
{
    "username": "Jim"
}